nodeLinker: node-modules
enableGlobalCache: true
nmMode: hardlinks-local

packageExtensions:
  "@vueuse/core@*":
    peerDependencies:
      vue: "*"
  "@vueuse/shared@*":
    peerDependencies:
      vue: "*" 