nodeLinker: node-modules
enableGlobalCache: true
nmMode: hardlinks-local

packageExtensions:
  "@vueuse/core@*":
    peerDependencies:
      vue: "*"
  "@vueuse/shared@*":
    peerDependencies:
      vue: "*"
  "stylelint-config-recommended-vue@*":
    peerDependencies:
      stylelint: ">=15.0.0"
  "stylelint-config-standard@*":
    peerDependencies:
      stylelint: ">=15.0.0"
  "stylelint-config-standard-scss@*":
    peerDependencies:
      stylelint: ">=15.0.0" 