name = "cyberoller-web-configuration"
type = "webpack"
account_id = "your-account-id"
workers_dev = true

[site]
bucket = "./dist"
entry-point = "workers-site"

[build]
command = "yarn install --frozen-lockfile && yarn build:cf"
publish = "dist"

[build.environment]
NODE_VERSION = "16"
YARN_VERSION = "3.2.2"

[build]
upload.format = "service-worker" 