name = "your-project-name"
type = "webpack"
account_id = "your-account-id"
workers_dev = true

[site]
bucket = "./dist"
entry-point = "workers-site"

[build]
command = "yarn build dev"
upload.format = "service-worker" 